### ISSUE TITLE
fixity for orElse

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/bytesmith#3]
@mckeankylej writes:

> `orElse` needs to have a infix precedence... preferably higher than `<$>`

I believe that "lower" was intended. Since `<|>` has `infixl 3`, I'm thinking about using this for `orElse` as well. This would let users use `orElse` anywhere that they would use `<|>` with another parser-combinator library. Note that `<$>` has `infixl 4`, so this would treat:

    Foo <$> bar `orElse` baz

as

    Foo <$> (bar `orElse` baz)

@mckeankylej Is this the behavior you're looking for?

**Comment by mckeankylej** [comment]
Hum we shouldn't stray from the fixity of `(<|>)` my use case looked like: 
```
Foo <$> bar `orElse` Quix <$> baz
```
But I don't think this use case is important enough to merit diverging from `(<|>)`.

**Comment by mckeankylej** [comment]
Oh after thinking about my comment. My comment only makes sense if `orElse` has a lower precedence than `(<$>)`. So `3` should be good.

**Comment by mckeankylej** [comment]
Fixed in 962ea844f69da3a96d6845802a0dcf13b39efc59
